### ISSUE TITLE
top:0, bottom: 0, left: 0, right: 0 意思

### ISSUE THREAD

**Issue by zm8** [zm8/blog#104]
### 1. 理解
1. 对于子元素设置 top: 0, bottom: 0, 相当于把元素撑开成父元素的高度。
2. 对于子元素设置 left: 0, right: 0, 相当于把元素撑开成父元素的宽度。

![image](https://user-images.githubusercontent.com/32337542/73829236-9a784680-483d-11ea-9e5d-d79fc9c5c967.png)
![image](https://user-images.githubusercontent.com/32337542/73830381-93523800-483f-11ea-85a4-8d894d14cd64.png)

``` html
<!DOCTYPE html>
<html>

<style type="text/css">
    *{
        margin: 0;
        padding: 0;
    }
    body{
        margin: 100px;
    }
    .box{
        width: 200px;
        height: 200px;
        border: 1px solid blue;
        position: relative;
    }
    .box .cnt{
        background-color: red;
        position: absolute;
        /* top: 0;
        bottom: 0; */
        left: 0;
        right: 0;
    }
</style>
<body>
    <div class="box">
        <div class="cnt">a</div>
    </div>
</body>
</html>
```

### 2. 元素垂直居中
修改 .box .cnt 让元素垂直居中
``` css
.box .cnt{
    position: absolute;
    background-color: red;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;

    height: 100px;
    width: 100px;
    margin: auto;
}
```

![image](https://user-images.githubusercontent.com/32337542/73830180-2a6ac000-483f-11ea-8e55-8b8e80a6a904.png)
