### ISSUE TITLE
Flex 常用布局记录

### ISSUE THREAD

**Issue by zm8** [zm8/blog#189]
### 1. 自动撑满高度
``` html
		<div class="flex-container">
			<div class="box1"></div>
			<div class="box2"></div>
		</div>
```
``` css

.flex-container {
	width: 100vw;
	height: 100vh;
	display: flex;
	flex-direction: column;
}

.flex-container .box1 {
	height: 200px;
	background-color: red;
}

.flex-container .box2 {
	flex-grow: 1;
	background-color: blue;
}
```

### 2. 多层flex自动撑高不生效问题
解决方案是给 ```.flex-container .box2``` 设置 ```height: 0```

``` html
		<div class="flex-container">
			<div class="box1"></div>
			<div class="box2">
				<p>内容 p</p>
				<div class="box2-wrap">
					<ul>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
						<li>this is text</li>
					</ul>
				</div>
			</div>
		</div>
```

``` css
.flex-container {
	width: 100vw;
	height: 100vh;
	display: flex;
	flex-direction: column;
}

.flex-container .box1 {
	height: 200px;
	background-color: red;
}

.flex-container .box2 {
	flex-grow: 1;
	background-color: blue;

	display: flex;
	flex-direction: column;
	height: 0;
}

.flex-container .box2 p {
	background-color: pink;
	height: 200px;
}

.flex-container .box2 .box2-wrap {
	flex-grow: 1;
	overflow: auto;
}
```

参考地址:
https://mp.weixin.qq.com/s/TVxwQkIDs0hTV7gVqqXHRg
