### ISSUE TITLE
SCSS 基础

### ISSUE THREAD

**Issue by zm8** [zm8/blog#236]
## 前言
sass是最早出现的css预处理语言，有着比less更强大的功能。采用Ruby语言编写。

最初版本采用的是严格缩进的风格（不带大括号( {} )和分号( ; )，这一语法也导致一开始，sass并不太为开发者所接受）。

从 V3 版本开始放弃了缩进式的风格，并完全兼容普通的css代码，也因此从第三代开始，sass也被称为scss。

## 1.变量
sass 中的变量定义是以 **$** 开头。
``` scss
$blue : #1875e7;
div {
　color : $blue;
}
```

变量的值也可以引用其他变量:
``` scss
$color: red;
$border: 1px solid $color; // 引用了 $color
 
.box{
    border: $border
}
 
// 编译为
.box{
    border: 1px solid red;
}
```

属性名和值都使用变量, 写的时候 变量必须放在 **#{}** 里面:
``` scss
$value: "red";
 
.box_#{$value} {
    color: #{$value};
}
 
// 编译为：
.nav_red {
   color: red
}
```

## 2. 嵌套
scss 结合 css module 的一种写法:
``` tsx
// index.tsx
import styles from './index.module.scss';
function Comp(){
    return (
        <div className={styles.box}>
            <div className={styles.text}>
                你好
            </div>
            <div className={styles.para}>
                祖国
            </div>
        </div>
    );
}
```

``` scss
// css
.box {
    .text{
        margin: 100px;
    }
    .para{
        color: red;
    }
}
```

## 3.计算功能
``` scss
$var: 0.1;
 
.box {
    width: $var * 8rem;
    margin: $var + 0.3rem;
}
 
// 编译成
.box {
    width: 0.8rem;
    margin: 0.4rem;
}
```

## 4. 属性嵌套
注意下面的 border 后面要加个冒号。
``` scss
.box {
    border: {
        width: 1px;
        style: solid;
        color: red;
    }
}
 
// 会变编译成
.box {
    border-width: 1px;
    border-style: solid;
    border-color: red;
}
```
属性嵌套, 对于单独设置的子属性， 提供一种简写方式:
``` scss
.box {
  border: 1px solid #ccc {
    /* 单独设置的 子属性 */
     left: 0px;
     right: 0px;
  }
}
 
// 会变编译成
.box {
  border: 1px solid #ccc;
  border-left: 0px;
  border-right: 0px;
}
```

### 1. 继承
使用 @extend 继承一个 class
``` scss
.highlight {
    color: red;
}
 
.box {
    font-size: 30px;
    @extend .highlight;
}
 
// 编译成
.box {
    font-size: 12px;
    color: red;
}
```

### 2. Mixin
使用 @mixin 来定义一个代码块, 使用 @include 来调用这个代码块。

PS: 大家可以对比 extend 的方式
``` scss
@mixin highlight {
    color: red;
}
 
.box {
    font-size: 30px;
    @include highlight;
}
 
// 编译成
.box {
    font-size: 30px;
    color: red;
}
```

mixin 还可以指定参数和缺省值，像函数一样进行调用:
``` scss
@mixin highlight($val: red) {
    color: $val;
}
 
.box {
    font-size: 30px;
    @include highlight(blue);
}
 
// 编译成
.box {
    font-size: 30px;
    color: blue;
}
```

## 6. 高级语法
像js一样写条件语句和循环语句, 用的比较少。
