### ISSUE TITLE
【面试】—— CSS

### ISSUE THREAD

**Issue by zm8** [zm8/blog#274]
## div占满父级元素余下高度的几种方式
html 为:
``` html
<div class="container">
  <div class="one"></div>
  <div class="two"></div>
</div>
```
通用 css:
``` css
.container {
  height: 400px;
}
.one {
  height: 100px;
}
```

### 1. 使用calc 

```css
.two{
	height: calc(100% - 100px);	
}
```

### 2. 使用绝对定位实现

``` css
.container{
	position: relative;	
}

.two{
	position: absolute;
	top: 100px;
	right: 0;
	bottom: 0;
	left: 0;
	background: #ff0;
}
```

### 3. 使用 flex 
``` css
.container {
  display: flex;
  flex-direction: column /* 排列方向 */;
}

.two{
	flex-grow: 1;
}
```
