### ISSUE TITLE
CSS 常用记录

### ISSUE THREAD

**Issue by zm8** [zm8/blog#278]
## 图片引用的简写方法
``` css
.bg{
    background: url(xxx) no-repeat 0 0 / contain;
}
```
